pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/xcombaba/ttcmobile-project.git'
            }
        }
      stage('Build') {
            steps {
               sh ''' cd MywebApp && mvn clean package'''
            }
        }
      stage('Test') {
            steps {
                sh ' cd MywebApp && mvn test'
            }
        }
        
 stage('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: '43a37aed-28b0-460d-b03f-aa97f81bfe1c', path: '', url: 'http://54.173.218.200:8080/')], contextPath: 'myapp', war: '**/*.war'
            }
         }
      }
      
    }
    
